version: '3.8'
services:
  demo:
    image: nginx:latest
    container_name: nginx
    restart: always
    networks:
      - internet
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=internet"
      - "traefik.http.routers.nginx.rule=Host(`${NGINX_ADDRESS}`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
      - "traefik.http.routers.nginx.tls.certResolver=default"
      - "traefik.http.routers.nginx.tls=true"
networks:
  internet:
    external:
      name: internet